// <auto-generated />
using System;
using ArtShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtShop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200618122646_seedDbProducts")]
    partial class seedDbProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Cọ vẽ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Màu"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Giấy vẽ các loại"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bút"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("ArtShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ArtShop.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Httt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHeader");
                });

            modelBuilder.Entity("ArtShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Cọ vẽ lông sóc ART SECRET thân đen có 70% là cọ lông sóc tự nhiên nên không có hiện tượng rụng lông hay tòe cọ khi vẽ.Đầu cọ vuốt nhọn có thể vẽ tỉa nét, đồng thời cũng có độ ngậm nước rất tốt thích hợp cho loang tranh khổ rộng.Không bị biến dạng trong quá trình sử dụng, độ bền rất cao.Thích hợp vẽ tranh màu nước, gouache, poster, acrylic.",
                            ImgUrl = "\\img\\product\\1.jpg",
                            Price = 89000.0,
                            ProductName = "Cọ vẽ ART SECRET Mop lông sóc thân đen",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Cọ vẽ lông sóc ART SECRET thân gỗ có 70% là cọ lông sóc tự nhiên nên không có hiện tượng rụng lông hay tòe cọ khi vẽ. Đầu cọ vuốt nhọn có thể vẽ tỉa nét, đồng thời cũng có độ ngậm nước rất tốt thích hợp cho loang tranh khổ rộng. Không bị biến dạng trong quá trình sử dụng, độ bền rất cao. Thích hợp vẽ tranh màu nước, gouache, poster, acrylic.",
                            ImgUrl = "\\img\\product\\2.jpg",
                            Price = 88000.0,
                            ProductName = "Cọ vẽ ART SECRET Mop lông sóc thân gỗ",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Cọ nét ART SECRET lông sóc thân đen có 70% là cọ lông sóc tự nhiên nên không có hiện tượng rụng lông hay tòe cọ khi vẽ. Đầu cọ vuốt nhọn có thể vẽ tỉa nét, đồng thời cũng có độ ngậm nước rất tốt thích hợp cho loang tranh khổ rộng. Không bị biến dạng trong quá trình sử dụng, độ bền rất cao. Chuyên dụng trong tranh màu nước, màu Acrylic, màu bột",
                            ImgUrl = "\\img\\product\\3.jpg",
                            Price = 39000.0,
                            ProductName = "Cọ vẽ ART SECRET đầu Tròn lông sóc thân đen",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Lông cọ trong suốt, siêu mượt. Thiết kế gồm đầu cọ linh hoạt và thân cọ chứa nước. Thân cọ thiết kế vừa cầm, dễ mang theo. Tránh bơm màu trực tiếp có thể làm tắc ống dẫn nước.",
                            ImgUrl = "\\img\\product\\4.jpg",
                            Price = 74000.0,
                            ProductName = "Cọ Nước Waterbrush KURETAKE (thân ngắn)",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Lông cọ trong suốt, siêu mượt. Thiết kế gồm đầu cọ linh hoạt và thân cọ chứa nước. Thân cọ thiết kế vừa cầm, dễ mang theo. Tránh bơm màu trực tiếp có thể làm tắc ống dẫn nước.",
                            ImgUrl = "\\img\\product\\5.jpg",
                            Price = 83000.0,
                            ProductName = "Cọ Nước Waterbrush KURETAKE thân dài (size Lớn)",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "Bộ cọ vẽ ART SECRET vẽ sơn dầu và acrylic được làm từ Lông lợn được nuôi trong khu vực của thành phố Chungking của Trung Quốc - vốn được xem là chất liệu tốt nhất dành để vẽ tranh gouache, acrylic và đặc biệt là sơn dầu. Dòng cọ vẽ Sơn Dầu thường có đầu lông rất cứng, có thể dùng chung cho màu Acrylic, nhưng rất hạn chế khi sử dụng màu Gouche, KHÔNG SỬ DỤNG CHO MÀU NƯỚC.",
                            ImgUrl = "\\img\\product\\6.jpg",
                            Price = 199000.0,
                            ProductName = "Bộ cọ vẽ ART SECRET vẽ sơn dầu và acrylic 10 cây",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Cọ vẽ Thư Pháp ART SECRET làm từ lông Dê tự nhiên nên không có hiện tượng rụng lông hay tòe cọ. Đầu cọ vuốt nhọn có thể vẽ tỉa nét, đồng thời cũng có độ ngậm nước rất tốt thích hợp cho loang tranh khổ rộng. Không bị biến dạng trong quá trình sử dụng, độ bền rất cao. Thích hợp vẽ tranh màu nước, gouache, poster, acrylic.",
                            ImgUrl = "~\\img\\product\\7.jpg",
                            Price = 410000.0,
                            ProductName = "Bộ cọ Thư Pháp ART SECRET lông Dê",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Màu Nước NHŨ SUPERIOR với thiết kế mỗi thỏi màu được đựng trong một khay riêng và có thể gỡ ra khỏi bảng màu trong quá trình sử dụng. Bộ màu gồm những màu nhũ với tông màu ánh ngọc trai khác nhau, độ lên màu chuẩn và khả năng loang màu rộng, có thể dùng ngay màu gốc hoặc pha với các màu khác để có tông màu như ý. Bộ màu được đựng trong hộp nhưa tiện lợi, kèm theo một cọ nước, dễ dàng mang theo ra ngoài. Bảo quản mát, tránh nắng làm khô nứt màu.",
                            ImgUrl = "~\\img\\product\\8.png",
                            Price = 89000.0,
                            ProductName = "Bộ màu nước Nhũ 5/8 SUPERIOR",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "Màu Nước O.WIN được thiết kế dạng nén nhỏ gọn, được đựng trong hộp nhựa tiện lợi. Độ lên màu chuẩn và khả năng loang màu rộng, màu sắc tươi sáng không chứa chất độc hại, có thể dùng ngay màu gốc hoặc pha với các màu khác để có tông màu như ý. Có kèm 1 cọ nước, nắp hộp được chia ngăn dùng làm khay pha màu, tiện dụng giúp mang theo bên người khi ra ngoài hoặc đi học. ",
                            ImgUrl = "\\img\\product\\9.png",
                            Price = 155000.0,
                            ProductName = "Bộ màu nước 18/24 OWIN",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Description = "Màu Nước O.WIN dòng PRETTY EXCELLENT được thiết kế dạng nén nhỏ gọn, được đựng trong hộp thiếc có tông màu pastel nhã nhặn. Độ lên màu chuẩn và khả năng loang màu rộng, màu sắc tươi sáng không chứa chất độc hại, có thể dùng ngay màu gốc hoặc pha với các màu khác để có tông màu như ý. Có kèm 1 cọ nước nhỏ, nắp hộp được chia ngăn dùng làm khay pha màu,1  tiện dụng giúp mang theo bên người khi ra ngoài hoặc đi học.  Là sản phẩm lý tưởng làm quà tặng cho bạn bè, người thân trong các dịp lễ.",
                            ImgUrl = "\\img\\product\\10.png",
                            Price = 89000.0,
                            ProductName = "Bộ màu nước 24/36 PRETTY EXCELLENT",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Description = "Hãng MARIE được thành lập vào năm 1919, sau này hãng thành lập liên doanh và đổi tên là SHANGHAI SIIC MARIE PAINTING MATERIALS CO., LTD vào năm 1958. Các sản phẩm của Marie có mặt trên thị trường của các thành phố khác nhau trên khắp Trung Quốc và hơn 60 quốc gia trên thế giới, và đạt được chứng nhận chất lượng ISO 9001: 2000. Cái tên Marie's không chỉ nổi tiếng ở Trung Quốc mà ngày nay đã được công nhận là thương hiệu nổi tiếng của thị trường châu Âu và Mỹ.",
                            ImgUrl = "\\img\\product\\11.jpg",
                            Price = 10000.0,
                            ProductName = "Bút Marker MARIE'S màu Da",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "Dùng như chì thông thường, tô theo lớp để chỉnh độ màu. Có khả năng chống gãy ngòi vượt trội. hơn hẳn tất cả các dòng chì màu trên thế giới, chất lượng họa sĩ thế giới tin dùng, màu sắc tươi sáng dễ pha trộn. Thể hiện bản vẽ kiến trúc - kỹ thuật, vẽ manga, chibi, minh họa,...",
                            ImgUrl = "\\img\\product\\12.jpg",
                            Price = 161000.0,
                            ProductName = "Bộ bút chì màu Khô 24/36/48 FABER & CASTELL",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Description = "Không có mô tả...",
                            ImgUrl = "\\img\\product\\13.jpg",
                            Price = 216000.0,
                            ProductName = "Bộ bút chì màu Nước 24/36/48 FABER & CASTELL",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Description = "White Nights là màu nước chuyên nghiệp có chất lượng cao nhất kết hợp phương pháp truyền thống của các bậc thầy xưa với kỹ thuật sản xuất hiện đại để tạo ra những thỏi màu nước nổi tiếng ngày  nay. Các thỏi màu dẻo, cô đặc được sản xuất từ chất màu mền mịn và thêm chất kết dính Gum Arabic - vốn được công nhận là chất kết dính tự nhiên tốt nhất cho màu nước chuyên nghiệp. Bảng màu bao gồm chủ yếu là các sắc tố đơn sắc tinh tế và không phai theo thời gian. Màu bền, ăn giấy tốt .Sử dụng tốt nhất là trong vẽ tranh lụa. Dùng nhiều trong ngành Mỹ Thuật , Kiến trúc … Và giới Mỹ Thuật chuyên nghiệp",
                            ImgUrl = "\\img\\product\\14.jpg",
                            Price = 307000.0,
                            ProductName = "Bộ màu nước 12/24/36 WHITE NIGHTS",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Description = "Được thành lập hơn 70 năm, hãng Pentel tự hào đã cung cấp cho thế giới những sản phẩm chất lượng nhất. Pentel là công ty thiết bị văn phòng duy nhất nhận giải thưởng Deming Award về tiêu chuẩn chất lượng cao. Các sản phẩm từ bút chì bấm, chì than, gôm tẩy, bút vẽ, marker, vật liệu nghệ thuật... được sản xuất bởi các nhà máy thuộc sở hữu và giám sát của Pentel. Các sản phẩm của Pentel đều thân thiện với môi trường, có thể tái chế được. để tạo ra một môi trường lành mạnh hơn. Màu bột PENTEL rất dễ sử dụng, màu sắc sống động và độ lên màu tuyệt vời.  Có thể pha với nước để làm cho tranh vẽ mượt mà hơn hoặc làm tăng khả năng loang màu.",
                            ImgUrl = "\\img\\product\\15.jpg",
                            Price = 396000.0,
                            ProductName = "Bộ màu bột PENTEL Postercolors 12 màu",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            Description = "Không có mô tả...",
                            ImgUrl = "\\img\\product\\16.jpg",
                            Price = 246000.0,
                            ProductName = "Bộ màu bột PENTEL Postercolors 6 màu Cơ Bản (30ml)",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            Description = "Canson là một hãng sản xuất giấy mỹ thuật hàng đầu thế giới có bề dày lịch sử bắt đầu từ năm 1557. Trong hơn 450 năm, Canson luôn mang cảm hứng cho nghệ sĩ khắp thế giới ở mọi lứa tuổi, mọi đối tượng từ người mới bắt đầu hoặc họa sĩ chuyên nghiệp. Canson luôn khẳng định khẩu hiệu “giấy khơi nguồn cảm hứng từ năm 1557.” Các dòng sản phẩm của hãng được nhiều họa sĩ chọn dùng do mang những đặc tính tuyệt vời : giấy dễ sử dụng, không chứa axit nên giấy không bị oxi hóa khi lưu trữ trong thời gian dài, hạn chế bị ẩm hay nấm mốc, không chứa bất kỳ chất phụ gia làm giấy trắng quá mức gây ảnh hưởng tới người dùng.",
                            ImgUrl = "\\img\\product\\17.jpg",
                            Price = 54000.0,
                            ProductName = "Giấy vẽ Canson MOULIN Du ROY 100% cotton 300gsm 56 x 38cm",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 3,
                            Description = "Giấy hoàn toàn không chứa axit, không có chất làm sáng quang học, thân thiện với mội trường, độ trắng hoàn toàn tự nhiên giúp tăng thời gian bảo quản và lưu trữ tác phẩm được lâu hơn mà không bị ố vàng. Với những đặc điểm trên hãng đã được chứng nhận đạt tiêu chuẩn ISO 9706. Chuyên vẽ màu nước, màu Acrylic, màu bột, chì nước",
                            ImgUrl = "\\img\\product\\18.jpg",
                            Price = 22000.0,
                            ProductName = "Giấy vẽ Màu Nước HAPPY 300gsm",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            Description = "anson là một hãng sản xuất giấy mỹ thuật hàng đầu thế giới có bề dày lịch sử bắt đầu từ năm 1557. Trong hơn 450 năm, Canson luôn mang cảm hứng cho nghệ sĩ khắp thế giới ở mọi lứa tuổi, mọi đối tượng từ người mới bắt đầu hoặc họa sĩ chuyên nghiệp. Canson luôn khẳng định khẩu hiệu “giấy khơi nguồn cảm hứng từ năm 1557.” Các dòng sản phẩm của hãng được nhiều họa sĩ chọn dùng do mang những đặc tính tuyệt vời : giấy dễ sử dụng, không chứa axit nên giấy không bị oxi hóa khi lưu trữ trong thời gian dài, hạn chế bị ẩm hay nấm mốc, không chứa bất kỳ chất phụ gia làm giấy trắng quá mức gây ảnh hưởng tới người dùng.",
                            ImgUrl = "\\img\\product\\19.jpg",
                            Price = 45000.0,
                            ProductName = "Giấy vẽ Canson PHÁP 125gsm",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            Description = "Giấy không vân, mịn, giấy có kẻ sẵn khung tranh để vẽ truyện. Bề mặt giấy trơn nhẵn, vẽ mượt mà, giúp ngòi bút vẽ lâu bị mòn hơn. Giấy dai, chống sờn, gôm tẩy chì phác thảo thoải mái.",
                            ImgUrl = "\\img\\product\\20.png",
                            Price = 77000.0,
                            ProductName = "Giấy vẽ Truyện Tranh HOLBEIN Maxon Standard Manga 110g A4",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 4,
                            Description = " Không có mô tả...",
                            ImgUrl = "\\img\\product\\21.jpg",
                            Price = 24000.0,
                            ProductName = "Bút đi nét MICRON SAKURA",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 4,
                            Description = "Không có mô tả...",
                            ImgUrl = "\\img\\product\\22.jpg",
                            Price = 29000.0,
                            ProductName = "Bộ bút sắt SKYISTS (2 cây)",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 4,
                            Description = "Không có mô tả...",
                            ImgUrl = "\\img\\product\\23.jpg",
                            Price = 65000.0,
                            ProductName = "Bút chì bấm PENTEL",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 4,
                            Description = " Bút có 2 đầu: 1 đầu nét và 1 đầu dẹp. Phù hợp với nhiều nét vẽ khác nhau. Mực gốc cồn, có chất lượng mực in được cải tiến hơn. Có thể sử dụng kết hợp với các loại bút marker gốc cồn khác. Màu không chứa Axit và không có mùi khó chịu.",
                            ImgUrl = "\\img\\product\\24.jpg",
                            Price = 200000.0,
                            ProductName = "Bộ Bút Marker 24 TOUCHLIIT",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 4,
                            Description = " Bút có 2 đầu: 1 đầu nét và 1 đầu dẹp. Phù hợp với nhiều nét vẽ khác nhau. Mực gốc cồn, có chất lượng mực in được cải tiến hơn. Có thể sử dụng kết hợp với các loại bút marker gốc cồn khác. Màu không chứa Axit và không có mùi khó chịu.",
                            ImgUrl = "\\img\\product\\25.jpg",
                            Price = 1722000.0,
                            ProductName = "Bộ Bút Marker TOUCHLIIT 200 màu",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 5,
                            Description = "Kê giấy vẽ, có tay cầm tiện dụng. Tuyết đối không ngâm bảng vẽ trong nước hoặc phơi bảng ngoài nắng sẽ làm cong sản phẩm.",
                            ImgUrl = "\\img\\product\\26.png",
                            Price = 50000.0,
                            ProductName = "Bảng vẽ ARTDOOR gỗ tự nhiên (3 lớp)",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 5,
                            Description = "Giá vẽ ART SECRET Nhỏ xách tay với thiết kế thêm ngăn kéo dùng đựng màu và dụng cụ vẽ tiện lợi khi mang theo ra ngoài, cấu trúc kiểu chống sau, có nhiều mức nghiêng để điều chỉnh được độ nghiêng phù hợp với mọi góc vẽ. Sản phẩm phù hợp cho nhu cầu vẽ tranh khổ nhỏ, có thể đặt trực tiếp trên bàn để vẽ.",
                            ImgUrl = "\\img\\product\\27.jpg",
                            Price = 462000.0,
                            ProductName = "Giá vẽ ART SECRET Nhỏ xách tay có ngăn kéo",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 5,
                            Description = "Giá vẽ ART SECRET Mini với thiết kế gỗ nhỏ gọn, dễ thương, cấu trúc kiểu khung đế chịu lực tốt. Sản phẩm phù hợp cho nhu cầu vẽ tranh khổ nhỏ, có thể đặt trực tiếp trên bàn để vẽ.",
                            ImgUrl = "\\img\\product\\28.jpg",
                            Price = 145000.0,
                            ProductName = "Giá vẽ ART SECRET Mini để bàn",
                            Status = "0"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 5,
                            Description = "Không có mô tả...",
                            ImgUrl = "\\img\\product\\29.jpg",
                            Price = 65000.0,
                            ProductName = "Cặp A3 (màu đen)",
                            Status = "0"
                        });
                });

            modelBuilder.Entity("ArtShop.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ArtShop.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("ArtShop.Models.OrderDetail", b =>
                {
                    b.HasOne("ArtShop.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtShop.Models.OrderHeader", b =>
                {
                    b.HasOne("ArtShop.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtShop.Models.Product", b =>
                {
                    b.HasOne("ArtShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
